apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: busybox
        image: busybox:1
        command: ["sh",  "-c", "sleep 3600; exit 0"]	
